#!/bin/sh
echo "postinst"
deb-systemd-helper unmask pisugar-server.service > /dev/null || true
if deb-systemd-helper --quiet was-enabled pisugar-server.service
then
	deb-systemd-helper enable pisugar-server.service > /dev/null || true
	deb-systemd-invoke start pisugar-server.service
else
	deb-systemd-helper update-state pisugar-server.service > /dev/null || true
fi