#!/bin/sh -e

. /usr/share/debconf/confmodule

db_input critical pisugar-server/led || true
db_go

db_input medium pisugar-server/address || true
db_go

db_input medium pisugar-server/web || true
db_go

db_input medium pisugar-server/tcp || true
db_go

db_input medium pisugar-server/uds || true
db_go