name: PR

on:
  pull_request:
    branches: [master]

jobs:
  build-web:
    uses: ./.github/workflows/build-web.yml
  build-cross:
    needs:
      - build-web
    uses: ./.github/workflows/build-cross.yml
  build-other:
    uses: ./.github/workflows/build-other.yml
